name: TeleportCompass
version: 1.0
api-version: 1.20
main: com.badlyac.TeleportCompassMain
commands:
  addLocation:
    usage: /addLocation <Location name> <Location X> <Location Y> <Location Z>
    description: Saves a location to the config
